// <auto-generated />
using System;
using MagicVilla.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla.Service.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MagicVilla.Service.Models.Villa.VillaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Villa");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7b65d2c-12e6-4fd7-a689-b2958119009f"),
                            Amenities = "Pool, Gym, Bar",
                            Area = 750.00m,
                            CreatedDate = new DateTime(2022, 8, 10, 14, 29, 15, 717, DateTimeKind.Local).AddTicks(3623),
                            Details = "Unmatched authentic luxury.",
                            ImageUrl = "https://e8rbh6por3n.exactdn.com/sites/uploads/2020/05/villa-la-gi-thumbnail.jpg?strip=all&lossy=1&ssl=1",
                            LastUpdate = new DateTime(2022, 8, 10, 14, 29, 15, 717, DateTimeKind.Local).AddTicks(3634),
                            Name = "Bliss View",
                            Occupancy = 5,
                            Rate = 500.00m
                        },
                        new
                        {
                            Id = new Guid("27ee7595-1fb9-4678-b8bf-d19e7e1793c3"),
                            Amenities = "Pool, Gym, Bar",
                            Area = 1000.00m,
                            CreatedDate = new DateTime(2022, 8, 10, 14, 29, 15, 717, DateTimeKind.Local).AddTicks(3638),
                            Details = "Moment Creating.",
                            ImageUrl = "https://e8rbh6por3n.exactdn.com/sites/uploads/2020/05/villa-la-gi-thumbnail.jpg?strip=all&lossy=1&ssl=1",
                            LastUpdate = new DateTime(2022, 8, 10, 14, 29, 15, 717, DateTimeKind.Local).AddTicks(3638),
                            Name = "Mountain View",
                            Occupancy = 3,
                            Rate = 1000.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
